name: BanSharePlugin
version: @version@
main: xyz.n7mn.dev.banshareplugin.BanSharePlugin
authors: [ 7mi_chan ]
description: BanSharePlugin
database: true
commands:
  gban:
    usage: '/gban'
    permission: '7misys.ban'
  lban:
    usage: '/lban'
    permission: '7misys.ban'
  unban:
    usage: '/unban'
    permission: '7misys.unban'