name: BanSharePlugin
version: @version@
main: xyz.n7mn.dev.banshareplugin.BanSharePlugin
authors: [ 7mi_chan ]
description: BanSharePlugin for 1.16.5
database: true
api-version: 1.16
commands:
  gban:
    usage: '/gban'
    permission: '7misys.ban'
  unban:
    usage: '/unban'
    permission: '7misys.unban'
  baninfo:
    usage: '/baninfo'
    permission: '7misys.info'
  report:
    usage: '/report'
  r:
    usage: '/report'